### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by vikingo12** [Ietu/pirate-perfection#2]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      kernel32  (???)     WaitForSingleObject                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                trainer/keybinded/xray.lua:260                      
                      xpcall()                                                      
                          =[C]  safecall()                                          
                                trainer/tools/marylog.lua:273                       
trainer/experimental/kbinput.lua:126  pcall()                                             
                          =[C]                                                      
trainer/tools/pubinfloopv2.lua:143  
-------------------------------

FYI I binded xray to C

**Comment by Ietu** [comment]
You have messed up something. Rebinding works perfectly fine for me when changed from the keyconfig.lua, even 'c' key works.

**Comment by vikingo12** [comment]
> You have messed up something. Rebinding works perfectly fine for me when changed from the keyconfig.lua, even 'c' key works.

I'm not saying it crashes because I changed the hotkey, It may have crashed due to large amount of enemies present on the map, cause I was playing cook off and when I pressed the x-ray button during assault it crashed
